# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1e34a270a881d04fbf12a3b6e2685afab9037c50336f3c39368a1f33815d4493e873ab8c67d3f86e0be1553a48a496019748bff85431927abc17d94707ec620

test:
  secret_key_base: 80aa5aa2c71da053791f398d5566fde65a0af4600ad6bfa7128b84ef8ae5191f7e4ce2f383600dd9d3e536af1a446dffa55012cf31cbd10e93b29949e3e906f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
